### ISSUE TITLE
Could not determine the dependencies

### ISSUE THREAD

**Issue by df13954** [XanderWang/performance#2]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.xander.performance:perf:0.1.9.
     Required by:
         project :app

**Comment by XanderWang** [comment]
不好意思啊，中间改了下库的

可以先用

dependencies {
  debugImplementation "com.xander.performance:p-tool:0.1.8"
  releaseImplementation "com.xander.performance:p-tool-noop:0.1.8"
}

来代替

**Comment by xanderwang** [comment]
已经同步到 jcenter 了，这个问题先关闭了。
