### ISSUE TITLE
about fps monitor

### ISSUE THREAD

**Issue by panda912** [XanderWang/performance#3]
个人感觉api24以上可以使用Window#addOnFrameMetricsAvailableListener来统计，比Choreographer更精确一点，因为当屏幕无变化的时候，vsync信号还是一直在发的，使用Choreographer的方式可能会导致统计偏高。在androidx.core已经帮我们实现好了FrameMetricsAggregator。

**Comment by xanderwang** [comment]
感谢反馈，我学习下。
