### ISSUE TITLE
配置依赖库一直报错，希望leader 帮忙解决下

### ISSUE THREAD

**Issue by bimromatic** [XanderWang/performance#4]
一直抱这个错误不知道啥原因
<img width="775" alt="13B3CEA5-C6B2-45CD-88BB-CFDC0474B6EC" src="https://user-images.githubusercontent.com/13240754/108654414-96c86800-7503-11eb-98e2-cca903f0ee01.png">

**Comment by xanderwang** [comment]
貌似是 gradle 设置了 offline mode ，你先试试关闭 offline mode ，sync 工程后试试
