### ISSUE TITLE
能否增加运行期间方法耗时

### ISSUE THREAD

**Issue by 877898444** [XanderWang/performance#6]
冷启动期间的运行方法耗时也是一个重要的点，针对运行期间的方法耗时能否增加检测？

**Comment by xanderwang** [comment]
不是特别了解你的需求，你是需要检测所有的方法耗时吗？还是部分指定的方法？

**Comment by liwei49699** [comment]
方法耗时过长会检测出来吗 会检测出UI卡顿？

**Comment by xanderwang** [comment]
@liwei49699  可以检测 ui 卡顿问题，但是不能检测所有的方法耗时。
